{{- if .Values.ingress.enabled -}}
  {{- $usePath := .Values.ingress.usePath -}}
  {{- $namespace := .Release.Namespace -}}
  {{- $workflow := .Values.workflow -}}
  {{- $serviceName := include "servicename" . -}}
  {{- $servicePort := .Values.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  {{- range $key, $value := .Values.ingress.annotations }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Values.image.tag }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "name" . }}
spec:
  rules:
  {{- if eq $namespace $workflow }}
  {{- if .Values.ingress.hostBased }}
  {{- range .Values.ingress.hostBased.hosts }}
  - host: {{ . }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
  {{- end -}}
  {{- end -}}
  {{- end }}
  tls:
  {{- if eq $namespace $workflow }}
  {{- if .Values.ingress.hostBased }}
  {{- if .Values.ingress.hostBased.tls }}
{{ toYaml .Values.ingress.hostBased.tls | indent 2 }}
  {{- end -}}
  {{- end -}}
  {{- end }}
{{- end -}}
